Repository JVitorCarv/simple-graphs, pull requests merged in 2023-11, with the labels that each got.

#1 Add footer
  src/assets/cytoscape.png
  src/assets/github.png
  src/components/Footer/Footer.tsx
  src/components/Footer/styles.ts
  src/components/GraphEditor/EditorContainer/components/RenderIcon/RenderIcon.tsx
  src/components/NetworkGraph/NetworkGraph.tsx
  src/components/NetworkGraph/styles.ts
Labels: enhancement

#2 Kryno
  package-lock.json
  package.json
  src/components/Footer/Footer.tsx
  src/components/Footer/components/modal/modalComponent.tsx
  src/components/Footer/styles.ts
  src/components/GraphEditor/EditorContainer/EditorContainer.tsx
  src/components/GraphEditor/EditorContainer/components/Button/Button.ts
  src/components/GraphEditor/EditorContainer/components/MainButton/MainButton.ts
  src/components/GraphEditor/Editors/EdgeEditor/components/AddEdge/AddEdge.tsx
  src/components/GraphEditor/Editors/EdgeEditor/components/CleanEdges/CleanEdges.tsx
  src/components/GraphEditor/Editors/EdgeEditor/components/EditEdge/EditEdge.tsx
  src/components/GraphEditor/Editors/NodeEditor/components/CleanNodes/CleanNodes.tsx
  src/components/GraphEditor/Editors/NodeEditor/components/EditNode/EditNode.tsx
Labels: enhancement

#6 Refactoring Dijkstra implementation to improve reusability
  src/components/GraphEditor/EditorContainer/components/Button/Button.ts
  src/components/GraphEditor/EditorContainer/components/MenuButton/MenuButton.tsx
  src/components/GraphEditor/EditorContainer/components/MenuButton/styles.ts
  src/components/GraphEditor/Editors/AlgorithmsEditor/AlgorithmsEditor.tsx
  src/components/GraphEditor/Editors/AlgorithmsEditor/components/DijkstraAlgorithm/DijkstraAlgorithm.tsx
  src/components/GraphEditor/Editors/AlgorithmsEditor/styles.ts
  src/components/GraphEditor/Editors/MoreInfosEditor/MoreInfosEditor.tsx
  src/components/GraphEditor/Editors/MoreInfosEditor/SizeOrderEditor/SizeOrderEditor.tsx
Labels: refactor

#8 Implement check for adjacency between 2 given nodes
  src/components/GraphEditor/Editors/MoreInfosEditor/CheckAdjacency/CheckAdjacency.tsx
  src/components/GraphEditor/Editors/MoreInfosEditor/CheckAdjacency/styles.ts
  src/components/GraphEditor/Editors/MoreInfosEditor/MoreInfosEditor.tsx
Labels: enhancement

#9 Make direction info global
  src/App.tsx
  src/components/Footer/Footer.tsx
  src/components/Footer/styles.ts
  src/components/GraphEditor/EditorContainer/EditorContainer.tsx
  src/components/GraphEditor/EditorContainer/components/SelectDirection/SelectDirection.tsx
  src/components/GraphEditor/EditorContainer/components/SelectDirection/styles.ts
  src/components/GraphEditor/EditorContainer/styles.ts
  src/components/GraphEditor/Editors/AlgorithmsEditor/components/DijkstraAlgorithm/DijkstraAlgorithm.tsx
  src/components/GraphEditor/Editors/EdgeEditor/components/AddEdge/AddEdge.tsx
  src/components/GraphEditor/Editors/MoreInfosEditor/CheckAdjacency/styles.ts
  src/providers/DirectionProvider.tsx
Labels: bug, enhancement

#10 Implemation node degree
  src/components/GraphEditor/Editors/MoreInfosEditor/CheckDegree/CheckDegree.tsx
  src/components/GraphEditor/Editors/MoreInfosEditor/CheckDegree/styles.ts
  src/components/GraphEditor/Editors/MoreInfosEditor/MoreInfosEditor.tsx
Labels: enhancement

#11 Add button to get adjacent nodes
  src/components/GraphEditor/Editors/MoreInfosEditor/CheckDegree/styles.ts
  src/components/GraphEditor/Editors/MoreInfosEditor/GetAdjacentNodes/GetAdjacentNodes.tsx
  src/components/GraphEditor/Editors/MoreInfosEditor/MoreInfosEditor.tsx
Labels: enhancement
